# Generated by Django 2.2.2 on 2019-06-24 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='  Up to 10 digits allowed.', regex='^\\+?1?\\d{10,15}$')])),
                ('user_type', models.CharField(choices=[('SP', 'Speaker'), ('AT', 'Attendant'), ('AD', 'Admin')], max_length=10)),
                ('profile_picture', models.FileField(blank=True, upload_to='', verbose_name='app-logo')),
                ('facebook_link', models.CharField(blank=True, max_length=30)),
                ('github_link', models.CharField(blank=True, max_length=30)),
                ('linkedIn_link', models.CharField(blank=True, max_length=30)),
                ('twitter_link', models.CharField(blank=True, max_length=30)),
                ('google_link', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
