# Generated by Django 2.0.5 on 2018-12-02 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='  Up to 10 digits allowed.', regex='^\\+?1?\\d{10,15}$')])),
                ('user_type', models.CharField(choices=[('SP', 'Speaker'), ('AT', 'Attendant'), ('AD', 'Admin')], max_length=10)),
                ('profile_picture', models.FileField(blank=True, upload_to='')),
                ('facebook_link', models.CharField(blank=True, max_length=30)),
                ('github_link', models.CharField(blank=True, max_length=30)),
                ('linkedIn_link', models.CharField(blank=True, max_length=30)),
                ('twitter_link', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('conference_code', models.CharField(max_length=30)),
                ('conference_organizer', models.CharField(max_length=30)),
                ('conference_image', models.FileField(blank=True, upload_to='', verbose_name='app-logo')),
                ('conference_name', models.CharField(max_length=30)),
                ('conference_location', models.CharField(blank=True, max_length=30)),
                ('conference_description', models.TextField(blank=True)),
                ('conference_start_date', models.DateField()),
                ('conference_end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'conference_details',
                'verbose_name_plural': 'conferences',
            },
        ),
        migrations.CreateModel(
            name='ConferenceAttendants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Conference')),
                ('conference_attendant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conference_attendant',
                'verbose_name_plural': 'conference_attendants',
            },
        ),
        migrations.CreateModel(
            name='ConferenceFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('conference_feedback_msg', models.TextField()),
                ('conference_attendant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Conference')),
            ],
            options={
                'verbose_name': 'conference_feedback',
                'verbose_name_plural': 'conference_feedback',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('session_name', models.CharField(max_length=30)),
                ('session_description', models.TextField(blank=True)),
                ('session_location', models.CharField(blank=True, max_length=30)),
                ('session_startTime', models.DateTimeField()),
                ('session_endTime', models.DateTimeField()),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Conference')),
                ('session_speaker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionAttendants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('attendance_status', models.BooleanField(default=False)),
                ('session_attendant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Session')),
            ],
            options={
                'verbose_name': 'session_attendant',
                'verbose_name_plural': 'session_attendants',
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('session_feedback_msg', models.TextField()),
                ('session_attendant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Session')),
            ],
            options={
                'verbose_name': 'session_feedback',
                'verbose_name_plural': 'session_feedback',
            },
        ),
        migrations.CreateModel(
            name='SessionForumResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('forum_response_msg', models.TextField()),
                ('session_attendant_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session_forum_responses',
                'verbose_name_plural': 'session_forum_responses',
            },
        ),
        migrations.CreateModel(
            name='SessionForumTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('forum_topic_msg', models.TextField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Session')),
                ('session_speaker_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session_forum_topic',
                'verbose_name_plural': 'session_forum_topics',
            },
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('title', models.CharField(max_length=30)),
                ('session_material', models.FileField(upload_to='')),
                ('session_material_description', models.TextField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Session')),
            ],
            options={
                'verbose_name': 'session_material',
                'verbose_name_plural': 'session_materials',
            },
        ),
        migrations.CreateModel(
            name='SessionSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Session')),
                ('session_speaker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session_speaker',
                'verbose_name_plural': 'session_speaker',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('tag_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='sessionforumresponses',
            name='session_forum_topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.SessionForumTopic'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_tag_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Tag'),
        ),
    ]
