# Generated by Django 2.0.5 on 2018-12-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceattendants',
            name='attendants_status',
            field=models.BooleanField(default=False),
        ),
    ]
