# Generated by Django 2.2.2 on 2019-06-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='linkedIn_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_type',
        ),
    ]
