# Generated by Django 2.0.5 on 2018-12-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181203_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceattendants',
            options={'verbose_name': 'Conference Attendant', 'verbose_name_plural': 'Conference Attendants'},
        ),
        migrations.AlterModelOptions(
            name='sessionattendants',
            options={'verbose_name': 'Session Attendant', 'verbose_name_plural': 'Session Attendants'},
        ),
        migrations.RenameField(
            model_name='sessionattendants',
            old_name='attendance_status',
            new_name='session_attendance_status',
        ),
    ]
