# Generated by Django 2.0.5 on 2018-12-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181203_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionfeedback',
            options={'verbose_name': 'Session Feedback', 'verbose_name_plural': 'Session Feedback'},
        ),
    ]
