# Generated by Django 2.0.5 on 2018-12-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181203_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='sessionforumresponses',
            options={'verbose_name': 'Session Forum Responses', 'verbose_name_plural': 'Session Forum Responses'},
        ),
        migrations.AlterModelOptions(
            name='sessionforumtopic',
            options={'verbose_name': 'Session Forum Topic', 'verbose_name_plural': 'Session Forum Topics'},
        ),
        migrations.AlterModelOptions(
            name='sessionmaterial',
            options={'verbose_name': 'Session Material', 'verbose_name_plural': 'Session Materials'},
        ),
        migrations.AlterModelOptions(
            name='sessionspeaker',
            options={'verbose_name': 'Session Speaker', 'verbose_name_plural': 'Session Speakers'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
