# Generated by Django 2.0.5 on 2018-12-07 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='  Up to 10 digits allowed.', regex='^\\+?1?\\d{10,15}$')]),
        ),
    ]
