# Generated by Django 2.0.5 on 2018-12-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_session_session_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='', verbose_name='app-logo'),
        ),
    ]
