# Generated by Django 2.0.5 on 2018-12-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181210_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='google_link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
